name: docker login

on: push
jobs:
    docker_job:
        runs-on: ubuntu-latest
        steps:
            - name: docker login
              uses: docker/login-actions@v3
              with:
                username: ${{ vars.Docker_Username }}
                password: ${{ secrets.Docker_Password }}
